spring:
  config:
    import: "classpath:env.yml"
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.h2.Driver
  exposed:
    generate-ddl: true