spring:
  profiles:
    default: dev
  config:
    import: "file:./data/${spring.profiles.active}.env.yml"
  datasource:
    url: ${DB.url}
    username: ${DB.username}
    password: ${DB.password}
    driver-class-name: ${DB.driver}
  exposed:
    generate-ddl: true
server:
  error:
    include-stacktrace: never
