spring:
  config:
    import: "classpath:env.yml"
  datasource:
    url: ${DB.url}
    username: ${DB.username}
    password: ${DB.password}
    driver-class-name: org.h2.Driver
  exposed:
    generate-ddl: true
server:
  error:
    include-stacktrace: never
app:
  files:
    storage: ${files.storage}
    location: ${files.location}
  admin:
    name: ${admin.name}
    password: ${admin.password}
    email: ${admin.email}