spring:
  config:
    import: "file:./data/${spring.profiles.active:default}.env.yml"
  datasource:
    url: ${DB.url}
    username: ${DB.username}
    password: ${DB.password}
    driver-class-name: ${DB.driver}
  exposed:
    generate-ddl: true
server:
  port: ${API.port:8080}
  error:
    include-stacktrace: never
